# Generated by Django 4.1.5 on 2023-01-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-published',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderwithoutauthor',
            options={'ordering': ('-published',), 'verbose_name': 'Заказ без автора', 'verbose_name_plural': 'Заказы без автора'},
        ),
    ]
