# Generated by Django 4.1.5 on 2023-01-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-published',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
